#!/bin/bash

# NOTE: Heroku Cedar Stack
#  gcc needs to be 4.3

# See http://cran.r-project.org/doc/manuals/R-admin.html for details on building R

# fail fast
set -e

# debug
 set -x

## HELPERS

function download() {
  if [ ! -f "$2" ]; then
    echo Downloading $2...
    curl $1 -o $2 -s -S
  else
    echo Got $2...
  fi
}

function build() {
  echo ----------------------------------------------------------------------
  echo Building $@...
  echo Vendordir $vendordir/$2 ${@:3}
  echo ----------------------------------------------------------------------
  echo
  pushd $1
    ./configure --prefix=$vendordir/$2 ${@:3} && make && make install && make clean
  popd > /dev/null
  echo
  echo

  # add to libraries and pkg-config
  export LD_LIBRARY_PATH="$vendordir/$2:$LD_LIBRARY_PATH"
  export PKG_CONFIG_PATH="$vendordir/$2/lib/pkgconfig:$PKG_CONFIG_PATH"

}

## SCRIPT

# upgrade from R V 2.15.1 to R Version 3.2.5
# r_version="${1:-2.15.1}"
# r_version_major=${r_version:0:1}
r_version="${1:-3.2.5}"
r_version_major=${r_version:0:5}
build_no=${3:-`date +%Y%m%d-%H%M`}

# check arguments
if ([ -z "$r_version" ] || [ -z "$build_no" ]); then
  echo
  echo "USAGE: $0 VERSION [BUILDNUM]"
  echo
  echo "  VERSION    is the R version. E.g. 3.2.5"
  echo "  BUILDNUM   the build number. E.g. 20131031-1400"
  echo
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# create output directory
vendordir=/app/vendor
mkdir -p $vendordir

echo ======================================================================
echo Downloading and unpacking dependancies...
echo ======================================================================

# http://www.freetype.org/freetype2/
freetype_version=2.5.0
download "http://www.mirrorservice.org/sites/download.savannah.gnu.org/releases/freetype/freetype-$freetype_version.tar.gz" freetype-$freetype_version.tar.gz
tar xzf freetype-$freetype_version.tar.gz

# http://directfb.org/
directfb_version=1.2.9
directfb_ver_major=${directfb_version:0:3}
download "http://directfb.org/downloads/Core/DirectFB-$directfb_ver_major/DirectFB-$directfb_version.tar.gz" DirectFB-$directfb_version.tar.gz
tar xzf DirectFB-$directfb_version.tar.gz

# http://www.libpng.org/pub/png/libpng.html
libpng_version=1.2.50
download "ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng12/libpng-$libpng_version.tar.gz" libpng-$libpng_version.tar.gz
tar xzf libpng-$libpng_version.tar.gz

# http://www.cairographics.org
pixman_version=0.30.2
download "http://www.cairographics.org/releases/pixman-$pixman_version.tar.gz" pixman-$pixman_version.tar.gz
tar xzf $basedir/pixman-$pixman_version.tar.gz

# http://www.freedesktop.org/software/fontconfig
fontconfig_version=2.10.93
download "http://www.freedesktop.org/software/fontconfig/release/fontconfig-$fontconfig_version.tar.gz" fontconfig-$fontconfig_version.tar.gz
tar xzf $basedir/fontconfig-$fontconfig_version.tar.gz

# http://www.cairographics.org
cairo_version=1.12.16
download "http://www.cairographics.org/releases/cairo-$cairo_version.tar.xz" cairo-$cairo_version.tar.xz
tar xJf $basedir/cairo-$cairo_version.tar.xz

# R
# download "http://cran.r-project.org/src/base/R-$r_version_major/R-$r_version.tar.gz" R-$r_version.tar.gz
# tar xzf R-$r_version.tar.gz
download "http://cran.r-project.org/src/base/R-3/R-3.2.5.tar.gz" R-3.2.5.tar.gz
tar xzf R-3.2.5.tar.gz

# http://gcc.gnu.org/wiki/GFortran
# changed gcc version from 4.3.6 to 4.9.3
# gcc_ver=4.3.6
gcc_ver=4.9.3
# gcc_version=${gcc_ver:0:3}
gcc_version=${gcc_ver:0:9}
# download "http://gfortran.com/download/x86_64/snapshots/gcc-$gcc_version.tar.xz" gcc-$gcc_version.tar.xz
# tar xJf $basedir/gcc-$gcc_version.tar.xz -C $vendordir
#download "http://gfortran.com/download/x86_64/snapshots/gcc-4.9.3.tar.xz" gcc-4.9.3.tar.xz
download "http://gfortran.meteodat.ch/download/x86_64/snapshots/gcc-5.tar.xz" gcc-5.tar.xz

tar xvf $basedir/gcc-5.tar.xz -C $vendordir

# patch gcc features.h file
# see http://permalink.gmane.org/gmane.comp.gcc.help/40166
mkdir -p $vendordir/gcc-4/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include-fixed
cp $basedir/features.h $vendordir/gcc-4/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/include-fixed/features.h
export LD_LIBRARY_PATH="$vendordir/gcc-4.9.3:$LD_LIBRARY_PATH"

# https://www.gnu.org/software/libc/
glibc_version=2.7
download "http://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz" glibc_2.23.tar.gz
tar xzf $basedir/glibc_2.23.tar.gz -C $vendordir

echo ============================================================
echo Building dependencies...
echo ======================================================================

build "$basedir/freetype-$freetype_version" freetype
build "$basedir/DirectFB-$directfb_version" DirectFB
build "$basedir/libpng-$libpng_version" libpng
build "$basedir/pixman-$pixman_version" pixman
build "$basedir/fontconfig-$fontconfig_version" fontconfig
build "$basedir/cairo-$cairo_version" cairo

# build R
echo ============================================================
echo Building R
echo ============================================================
pushd $basedir/R-3.2.5/

export LDFLAGS="-L$vendordir/gcc-4.9.3/lib64"
export CPPFLAGS="-I$vendordir/glibc-2.23/string -I$vendordir/glibc-2.23/time -I$vendordir/cairo/include/cairo/include"
export PATH="$vendordir/gcc-4.9.3/bin:$PATH"

echo ----------------------------------------------------------------------
echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH
echo PKG_CONFIG_PATH=$PKG_CONFIG_PATH
echo ----------------------------------------------------------------------

./configure --prefix=$vendordir/R --with-x --with-libpng --with-cairo --enable-R-shlib && make && make install

popd

# TODO: remove unneeded files to make buildpack smaller

# upload to S3 bucket
pushd $vendordir
tar czf "R-3.2.5-binaries-$build_no.tar.gz" freetype DirectFB libpng pixman fontconfig cairo R
popd

bundle exec ruby ./s3_upload.rb "$vendordir/R-3.2.5-binaries-$build_no.tar.gz"
