#!/bin/bash

# assuming `vulcan-setup` command has been run

rversion=3.2.5

rm build.tgz
tar czf build.tgz build-r features.h

vulcan build --source=./build.tgz \
             --prefix=/app/vendor \
             --command="./build-r $rversion" \
             --verbose
